### ISSUE TITLE
the `./dataset/SAMUS/CAMUS_full/class.json` is missing

### ISSUE THREAD

**Issue by jasonrichdarmawan** [dengxl0520/MemSAM#21]
# Commit: 
36f1b988f14b518a6346d2edb1267340387e646c

# Goal: 
run `$ python test_video.py`

# Issues:
- [x] the `medpy` package is not in the `requirements.txt`

   Error log
   ```
   (.venv) jason@Jasons-MacBook-Pro 02-MemSAM % python test_video.py
   Traceback (most recent call last):
     File "/Users/jason/01 Learn/Active/Programming/03 NPU/03 Large Model/02-MemSAM/test_video.py", line 20, in <module>
       from utils.evaluation import get_eval
     File "/Users/jason/01 Learn/Active/Programming/03 NPU/03 Large Model/02-MemSAM/utils/evaluation.py", line 12, in <module>
       from medpy.metric.binary import hd as medpy_hd
   ModuleNotFoundError: No module named 'medpy'
   ```

   Solution: run `$ pip3 install medpy`

- [ ] the `./dataset/SAMUS/CAMUS_full/full.json` is missing

   The `CAMUS_full` is not mentioned in the `README.md` file and the mentioned `CAMUS` dataset don't have `class.json`

   Error log
   ```
   (.venv) jason@Jasons-MacBook-Pro 02-MemSAM % python test_video.py
   task CAMUS_Video_Full checkpoints: checkpoints/CAMUS_full/your_checkpoint.pth
   Traceback (most recent call last):
     File "/Users/jason/01 Learn/Active/Programming/03 NPU/03 Large Model/02-MemSAM/test_video.py", line 76, in <module>
       test_dataset = EchoVideoDataset(opt.data_path, opt.test_split,  tf_val, img_size=args.encoder_input_size, frame_length=10,disable_point_prompt=args.disable_point_prompt, point_numbers=args.point_numbers)  # return image, mask, and filename
     File "/Users/jason/01 Learn/Active/Programming/03 NPU/03 Large Model/02-MemSAM/utils/data_us.py", line 810, in __init__
       with open(self.class_dict_file, 'r') as load_f:
   FileNotFoundError: [Errno 2] No such file or directory: './dataset/SAMUS/CAMUS_full/class.json'
   ```

# What I've tried

1. Follow the [README.md usage section](https://github.com/dengxl0520/MemSAM?tab=readme-ov-file#usage)
    1. download the CAMUS dataset and extract it to the `./dataset` folder. E.g `./dataset/CAMUS_public`
    2. download the EchoNet dataset and extract it to the `./dataset` folder. E.g. `./dataset/EchoNet-Dynamic`
    3. preprocess the CAMUS dataset and extract it to the `./temp_dir` folder. E.g. `./temp_dir/CAMUS_public_256`
    4. preprocess the EchoNet dataset and extract it to the `./temp_dir` folder. E.g. `./temp_dir/EcoNet`

**Comment by AGreenApple2002** [comment]
臣附议

**Comment by judyinf** [comment]
You can check the answers in #6

**Comment by jasonrichdarmawan** [comment]
Closed, old age issue
